import { defineType } from "sanity";
import { img, obj, objList, seo, str, strList, txt } from "./helpers";

// Mirrors src/content/contact.ts, top to bottom of the Contact page.
export default defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  fields: [
    obj("hero", "1. Heading", [
      str("eyebrow", "Small Label"),
      str("heading", "Heading"),
      txt("subheading", "Description"),
    ]),
    obj("desks", "2. Contact Details (left column)", [
      str("eyebrow", "Small Label"),
      str("heading", "Heading"),
      txt("description", "Description", 2),
      str("phoneLabel", "Phone – Label"),
      str("phone", "Phone – Number"),
      str("phoneHours", "Phone – Hours"),
      str("whatsappLabel", "WhatsApp – Label"),
      str("whatsappNumber", "WhatsApp – Number Shown"),
      str("whatsappUrl", "WhatsApp – Link", { description: "e.g. https://wa.me/919820048300" }),
      str("whatsappBadge", "WhatsApp – Badge"),
      str("emailHeading", "Emails – Heading"),
      objList(
        "emails",
        "Emails",
        "emailRow",
        "Email",
        [str("label", "Label"), str("email", "Email Address")],
        "email",
      ),
      img("image", "Photo"),
      str("imageLabel", "Photo – Small Label"),
      str("imageCaption", "Photo – Caption"),
      str("hoursHeading", "Hours – Heading"),
      txt("hoursText", "Hours – Text", 3),
    ]),
    obj("form", "3. Enquiry Form (right column)", [
      str("eyebrow", "Small Label"),
      str("heading", "Heading"),
      txt("description", "Description", 2),
      strList("tabs", "Tabs", { description: "Three enquiry types." }),
      str("nameLabel", "Name – Label"),
      str("namePlaceholder", "Name – Placeholder"),
      str("emailLabel", "Email – Label"),
      str("emailPlaceholder", "Email – Placeholder"),
      str("phoneLabel", "Phone – Label"),
      str("phonePlaceholder", "Phone – Placeholder"),
      str("sanctuaryLabel", "Sanctuary – Label"),
      str("sanctuaryPlaceholder", "Sanctuary – Placeholder"),
      strList("sanctuaries", "Sanctuary Options"),
      str("intentLabel", "Intent – Label"),
      str("intentDefault", "Intent – Pre-filled Text"),
      str("datesLabel", "Dates – Label"),
      str("datesPlaceholder", "Dates – Placeholder"),
      str("messageLabel", "Message – Label"),
      txt("messagePlaceholder", "Message – Placeholder", 2),
      str("privacyNote", "Privacy Note"),
      str("submitLabel", "Submit Button"),
      txt("successMessage", "Thank-you Message", 2),
    ]),
    seo(),
  ],
  preview: {
    prepare: () => ({ title: "Contact Page" }),
  },
});
